name: Deploy

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with: 
          node-version: 16
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: laravel-test-db
          mysql user: laravel_test_user
          mysql password: example
      - name: Copy .env
        run: cp .env.example .env
      - name: Install composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Install node dependencies
        run: npm ci
      - name: Setup Project
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan key:generate
          npm run build
      - name: Directory Permissions
        run: chmod 755 -R storage bootstrap/cache
      - name: Deploy to Server
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ssh.gb.stackcp.com
          remote-user: jrdev.co.uk
          private-ssh-key: ${{ secrets.SSH_KEY }}
          destination-path: ~/